### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by MattLoy** [IshtarStar/docker-compose-nginx-phpfpm#1]
Might want to change

  - "./docker/nginx/nginx.conf:/etc/nginx/conf/default.conf"
  - to
 "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"

In docker-compose.yml. 

NGINX is looking for conf.d not conf

**Comment by IshtarStar** [comment]
Hi @MattLoy .

Thank you. I fixed that in https://github.com/IshtarStar/docker-compose-nginx-phpfpm-xdebug-mariadb/blob/master/docker-compose.yml

Kind regards
Marc
